[project]
name = "cpubound"
version = "0.1.0"
description = "Test out Python 3.14 free-threading (nogil) build"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ipython>=9.5.0",
]
